// Generated by CoffeeScript 1.9.1
(function() {
  var NodeObjectStream, f, fs, p, res;

  NodeObjectStream = require('./node-object-stream');

  fs = require('fs');

  f = fs.createReadStream('../file');

  p = f.pipe(new NodeObjectStream);

  res = 0;

  p.on('object', function(obj) {
    return ++res;
  });

  p.on('end', function() {
    return console.log(res);
  });

}).call(this);
