#!/bin/bash

procnum="$1"

if [ "$2" = "" ]; then
    lim=1
else
    lim="$2"
fi

all_sigs="$(kill -l | tr -s '\t' '\n' | sed -re 's/[0-9]+\)//g' -e 's/^\s+//g')"

for i in $(seq 1 $lim); do
    if ! [ -d "/proc/$procnum" ]; then exit; fi
    echo "$all_sigs" | while read sig; do
        if [ -d "/proc/$procnum" ]; then
            kill -s "$sig" "$procnum"
        else
            exit
        fi
    done
done
