#!/bin/bash

# $1: url of page with links to files
# $2: filetype extension to download

# positive lookbehind for links
paths_to_files_of_type="$(curl "$1" | grep -P -o "(?<=href=\").*$2")"

url_stripped_of_end="$(echo $1 | grep -o -P '.*(?=/)')"

while read -r line; do
    if [ "$(echo $line | grep "^http")" ]; then
        wget "$line"
    else
        wget "$url_stripped_of_end/$line"
    fi
done <<< "$paths_to_files_of_type"

echo "$(echo $paths_to_files_of_type | wc -l) files downloaded."
